### ISSUE TITLE
Typo in Readme section:  "How do I hook up a relay?"

### ISSUE THREAD

**Issue by VoltVisionFrenchy** [bobko69/8PortLEDDistro#2]
In the Readme section called "How do I hook up a relay?", it says "On the board by the USB-C connector there is a header labeled H1 with 5V, IO32 and GND".  On both v2 and v3, it is actually H4 and IO36.

**Comment by bobko69** [comment]
oh you know what at one point all the headers had 5v but i changed that at some point so you could use a microphone or temp sensor.  IO36 is read only so you cant use it to control a relay. (IO34, IO35, IO36, and IO39 are all read only)

you will have to use IO17, IO32 or IO33 on H1 to control the relay and pull 5v power from H4 hiding behind the ethernet port.

**Comment by bobko69** [comment]
alright i changed the read me to have the updated information.  thank you for pointing this out.
