### ISSUE TITLE
Update to 15.0 / segment names not saving 

### ISSUE THREAD

**Issue by r1b4z01d** [bobko69/8PortLEDDistro#3]
Any plan to update the firmware to 15.0? When I try it complains about using GPIO 12 and 14. My main reason for wanting to is to try to resolve a segment naming issue I have. I can rename it but when the device restarts it loose all the names.

**Comment by r1b4z01d** [comment]
read the README: 
https://github.com/bobko69/8PortLEDDistro/blob/main/README.md#i-cant-assign-gpio14-and-gpio15-after-loading-firmware-version-015x

**Comment by bobko69** [comment]
i hear there are still problems with 0.15 that they are still working through.   i will upgrade when they get them all fixed.  im not sure why GPIO12 is not working but i do know that GPIO14 and GPIO15 are assigned by default to the digital mic and need to be reassigned before they can be assigned to ports.  oh looks like you found how to do that in the FAQ page.

**Comment by r1b4z01d** [comment]
I think it is 14 and not 12. It was a late night thing and clearly did not read the README. Trying again now.

Thank you, I love the device. I have three 8X versions. Likely going to buy another very soon.

**Comment by r1b4z01d** [comment]
Actually I have four of them😺 
Upgrade to 15 worked with the directions in the README. You are correct 15.0 still has an issue saving the names. Oh well, Thanks again.

**Comment by r1b4z01d** [comment]
Workaround:

1. Name all the segments
2. Save as a preset
3. Set preset to apply at boot
       Settings~> LED Preferences~> "Apply preset '1' at boot"

**Comment by bobko69** [comment]
this is a clever solution!  thank you for posting this.
